development:
  smtp_domain: localhost:3000
  smtp_user_name: mywork@seanergysoftech.com
  smtp_password: Seanergy^9
  app_domain: http://182.75.34.147:3000/
  view_domain: http://182.75.34.146:5000/

production:
  smtp_domain: localhost:3000
  smtp_user_name: mywork@seanergysoftech.com
  smtp_password: Seanergy^9
  app_domain:
  view_domain:
