development:
  smtp_domain: localhost:3000
  smtp_user_name: mywork@seanergysoftech.com
  smtp_password: Seanergy^9
 
production:
  smtp_domain: localhost:3000
  smtp_user_name: mywork@seanergysoftech.com
  smtp_password: Seanergy^9